version: '3.8'
networks:
  default:
    external: true
    name: mainnet
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    # volumes:
    #   - ./dbdata:/var/lib/postgresql/data/

    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432

volumes:
  dbdata:

